# Service Post 설정
server:
  port: 9091

# Log Level 설정
logging:
  level:
    root: debug

---
# Redis Cluster 설정
#redis:
#  single:
#    node: ds-dev-redis-cluster-0001-001.ozro5e.0001.apn2.cache.amazonaws.com:6379

---
# Redis Cluster 설정
redis:
  cluster:
    nodes:
      ds-dev-redis-cluster-0001-001.ozro5e.0001.apn2.cache.amazonaws.com:6379
