# Service Post 설정
server:
  port: 9091

# Log Level 설정
logging:
  level:
    root: info

# Redis Stand Alone 설정
redis:
  stand-alone:
    host: localhost
    port: 6379

# Redis Cluster 설정
#redis:
#  cluster:
#    nodes:
#      127.0.0.1:6379