# Service Post 설정
server:
  port: 9091

# Log Level 설정
logging:
  level:
    root: info

# Redis 설정
spring:
  data:
    redis:
      host: localhost
      port: 6379

# Pub/Sub 설정
redis:
  pubsub:
    topic: messages
