# compose 파일 버전
version: '3'
services:
  # Redis Cluster 서비스
  redis-cluster:
    container_name: redis-cluster-6
    image: grokzen/redis-cluster:7.0.15
    environment:
      - IP=0.0.0.0  # 모든 네트워크 인터페이스를 수신
      - BIND_ADDRESS=0.0.0.0  # 모든 네트워크 인터페이스에 바인드
      - INITIAL_PORT=7001  # 초기 포트 번호
      - MASTERS=3  # 마스터 노드의 수
      - SLAVES_PER_MASTER=1  # 각 마스터 노드당 슬레이브 노드의 수
    ports:
      - "7001-7006:7001-7006"  # 호스트 포트와 컨테이너 포트 매핑
